services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.hashcat.nvidia
    image: dwpa-worker
    restart: always
    privileged: true
    volumes:
      - ./rules:/srv/app/rules
      - runtime:/srv/app/runtime
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  runtime: