FROM javydekoning/hashcat:latest

RUN apt-get update && apt-get install -y python3 wget screen

WORKDIR /srv/app

COPY --chown=root:root .docker/entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

VOLUME [ "/srv/app/runtime", "/srv/app/rules" ]

CMD [ "./entrypoint.sh" ]